services:
  agrigear-postgres:
    image: postgres:latest
    container_name: hellotractor-kradle-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hellotractor-kradle-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
